### ISSUE TITLE
Mount IP freezes 

### ISSUE THREAD

**Issue by fenriques** [mworion/MountWizzard3-DIST#1]
hello, first of all thanks for this very useful software.
Just bought my HPS1000 and playing with MountWizzard3 beta on Ubuntu Mate 16.04.
In Settings I was entering all connection params. All INDI configs work fine but whenever I enter a value in the Mount section the app freezes (have to force-quit).
Also on any file operation the app hangs (load, save etc). But if I manually edit the config.cfg file I can connect to the mount and everything seems to work.
Attached the log file.

Cheers
ferrante
[mount.2018-06-10.log](https://github.com/mworion/MountWizzard3-DIST/files/2087995/mount.2018-06-10.log)

**Comment by mworion** [comment]
Hi ferrante,

thanks for testing the software and the feedback. Try to address those issues. Hopefully I get another version out today which might improve the situation. The beta 4 was done without your input, so it will bring no improvement for your issue

**Comment by mworion** [comment]
Hi Ferrante,
beta 4 change FITS header policy if users don't setup their imaging app fully. MW tries from beta4 to reconstruct this data in all cases. This was missing.
With a Ubuntu 18.04 install I got it to reproduce, but no fix so far. This will take more time.

**Comment by fenriques** [comment]
ok thanks.
One more thing, please. I'm trying rigth now to update to beta 4 with the usual command, after apt update:
`ferrante@astropi:~$ python3.6 -m pip install mountwizzard3 --upgrade --no-cache-dir `
But no update seems to be available. Does it take some time to build and be available?
Note that I used 'python3.6 -m pip' because else it would use pip and not pip3.

**Comment by mworion** [comment]
...the pip topic should be of no hurdle.
I did some work, but not finally done. it's now beta 5 due to other bugfixes. Install should work

**Comment by fenriques** [comment]
downloaded beta5. It has changed installation dir. It was in ~/.local/lib e now  (as in documentation) in /usr/.local... I guess that there was in the previous version a conflict in permission on writing files.
Now with the new setup everything works! I can save / load / change values etc.
Thanks. I mark the issues as solved.
