### ISSUE TITLE
MW3-3.0b12 hangs on quit in High Sierra

### ISSUE THREAD

**Issue by Ginge70** [mworion/MountWizzard3-DIST#11]
From time to time MW3 becomes irresponsive when quitting. Haven't been able to isolate the cause, attaching the report after a 
[MW3 hang.pdf](https://github.com/mworion/MountWizzard3-DIST/files/2415117/MW3.hang.pdf)

forced quit.

**Comment by mworion** [comment]
Thanks this helps. Could you post the mount-yyyy-mm-dd.log file out of your working directory as well ?

**Comment by Ginge70** [comment]
Sure, here it is.

Ginge
[mount.2018-09-25.log](https://github.com/mworion/MountWizzard3-DIST/files/2416575/mount.2018-09-25.log)

**Comment by mworion** [comment]
Hi Ginge,

there are some improvements made in RC3. Please give it a try. Just download it from releases.

Michel

**Comment by Ginge70** [comment]
Very good. I'll use RC1

**Comment by mworion** [comment]
You mean RC3 right ?

**Comment by Ginge70** [comment]
Ah, it just appeared after I downloaded the RC1. 
Thanks

**Comment by mworion** [comment]
HI Ginge, 

anything new about this topic ?

**Comment by mworion** [comment]
Stability will be improved with version 4 and a new underlying architecture.
