### ISSUE TITLE
Astrometry.NET fails to solve

### ISSUE THREAD

**Issue by fenriques** [mworion/MountWizzard3-DIST#12]
hi Michel,
I'm trying to build a new model with MW3 beta after I made some changes to my remote setup.
I use astrometry.NET online solving option, the API is correct and I see on my astrometry online dashboard that the FIT file is uploaded and the job started. But after some minutes it always fails to solve.
As a test I also downloaded the failed FIT file from astrometry.NET and then manually uploaded: it succeeds. So it's not the FIT file itself.
Attached 2 logs: the _ko.txt is the failed attempt with MW3, the _ok.txt is the same file but manually uploaded.
Thanks,
Ferrante

astrometry_log_ok.txt](https://github.com/mworion/MountWizzard3-DIST/files/2416835/astrometry_log_ok.txt)
[astrometry_log_ko.txt](https://github.com/mworion/MountWizzard3-DIST/files/2416836/astrometry_log_ko.txt)

**Comment by mworion** [comment]
Hi Ferrante,

could you post the mount.yyyy-mm-dd.log as well ? As I had some troubles with astrometry, please use the latest version, RC3. This should solve some of the lasting issues.

Michel

**Comment by fenriques** [comment]
yes sorry I mentioned wrong version. I'm already using RC2.
Attached the log. There's a lot of other tests, not just the Astrometry solving. Could be a bit confusing.
[mount.2018-07-26.log](https://github.com/mworion/MountWizzard3-DIST/files/2416968/mount.2018-07-26.log)

**Comment by mworion** [comment]
Hi Ferrante,

definitiv a bug in. This won't be watched with RC3. From my first look, it seem to have the wrong setups for pixel size and focal length either in MountWizzard3 itself or EKOS/INDI. Could you post 
your config file = it is in /config and you named it santacristina.cfg.

Because this data is not there, the plate solver will take long time. You could set the timeout therefore in MW3 higher, but it should solve within 3-5 Minutes anyhow. If not I have to find out.
On thing in addition: could you also post on of the image files, which did not solve ?

Michel

**Comment by fenriques** [comment]
Pixel size and focal length are correct. I have an ASI071 on a 115/800 f7 refractor. 
Main parameters are (calculated and verified with plate solve):
Size:	1.72 x 1.15 deg
Radius:	1.035 deg
Pixel scale:	1.26 arcsec/pixel
Diagonal: 28.4mm
Resolution: 16Mega Pixels 4944X3284
Pixel Size: 4.78 microns

Attached my cfg file and a FIT, renamed jpeg, that MW3 did not solved (but if you manually upload it is ok)

[santacristina.cfg.txt](https://github.com/mworion/MountWizzard3-DIST/files/2417128/santacristina.cfg.txt)
![m33_light_300_secs_2018-09-25t21-17-35_003 fits](https://user-images.githubusercontent.com/38842860/46044471-21ca8b80-c11b-11e8-91bf-c4ca7de788b7.jpeg)

**Comment by fenriques** [comment]
one more thought not directly related to this bug. 
Ekos / INDI has a very good plate solving module based on Astrometry.NET. It can be used online on nova.astrometry.net or locally provided you download appropriate index files. I am quite sure you are aware of this. 
Would it be feasible to add an interface to this module in MW3?
More or less the same approach used for astrometry-api-lite but without the need to go through the installation of an additional software that has its own manager, controller etc.

**Comment by mworion** [comment]
Ferrante,
I'm sorry, I can't download the fits file. Maybe you could zip it before uploading. 
Second: please try to load the image with MW3 in Image Window and try to manual solve. 
Third: Out of your config I see that you may have a log level to warning (it's in settings / version menus). please set it to debug before the test and post the extended log as well.
Sorry for bothering.

Michel

**Comment by fenriques** [comment]
hi Michel,
don't bother! you are giving me (and many others) a great help in our common passion. We really have to thank you for the time you put on solving these issues.

Sky was not clear today so I just tested yesterday images with the manual solver.
I enabled debug level logging.

In the zip attached:
- 'mount.2018-09-26.log' the log with debug enabled.
- 'Model_Image_002.fit' an image captured yesterday during an 'initial model' attempt. Used for manual solving (failed).
- 'astrometry_lsolved_ok.txt' the log from astrometry.NET manual upload for the same image above.
- 'Light_300_secs_2018-09-25T21-17-35_003.fits' a 300s image captured with Ekos. It can be solved successfully both in MW3 (manual solve) and in astrometry.NET online. 

It seems there's an issue in the fits header data.
Ferrante
[MW3.zip](https://github.com/mworion/MountWizzard3-DIST/files/2421520/MW3.zip)

**Comment by fenriques** [comment]
hi Michel, 
I just discovered that the clock of the mount is out of sync. It runs about 80 min late. I do not the reason why it happened and why the INDI / Ekos client is not updating it.
Could it be the reason why MW is not solving?
My mount is at a remote site, I cannot adjust the clock and test if this was the issue. Could you try to change time on your mount and check if it solves?

**Comment by fenriques** [comment]
I was playing with all the options in 'Config model build' and setting 'astrometry radius' to 3.0 helped to solve!

**Comment by mworion** [comment]
Hi Ferrante,

so far I checked the logs: There is actually no miscalculation of the necessary data for solving. Still the INDI driver puts another Header entry "SCALE" to tell which resolution arcs / pixel the camera is about. Actually I've seen "PIXSCALE" with other drivers. So I will add "SCALE" as well. It's really bad that these header entries are not standardized. 

If you got it solved with an bigger radius, that's good to hear. Maybe it's an good idea to raise the default value fo radius in MW3. If you know, that it solver better, the user could lower that value.

Regarding time:  MW3 uses only the mount time for calculations, regardless which time you have on your computer. As the mount time has to be correct for usage, MW3 will be correct, too. 

So I would close this issue as solved.

There was another hidden bug in your log, which is not related for solving. I will address this as well in the next version.

Michel

**Comment by fenriques** [comment]
hi Michel,
I am progressively lowering the radius. So far I have reached 0.8 and it is still solving correctly.
I will test lower values next nights.
Yes, a default value for radius greater than zero would help.

Thanks
Ferrante
