### ISSUE TITLE
Scope behaves erratically after model build

### ISSUE THREAD

**Issue by nickym998** [mworion/MountWizzard3-DIST#13]
Hi there,

I tried to run a model last night and after the full model was complete.  The scope was slewing erratically around the sky.  The model was obviously corrupt and as soon as I hit "clear model", the scope stopped selling around.  I think that some failed model points (building or cloud in way) are ending up in the model with very high Dec difference which is in turn corrupting the model.  Please see attached log file.

Also, It would be really handy to have "shortcuts" to virtual handset menu options on a tab within Mount Wizzard.  This would allow quick access to functions such as "Balance" etc.

Many thanks,

Nick

[mount.2018-09-25.log](https://github.com/mworion/MountWizzard3-DIST/files/2419484/mount.2018-09-25.log)

**Comment by mworion** [comment]
Hi Nick,

you hit the border ! Congrats. Your model was at least 100 points. The mount computer only supports in max 100. Unfortunately I did not cover exceeding this limit. So data is going inconsistent. It's a bug. I have to cover this extrem situation. Point over 100 should be just left out.

Will be corrected in the next version. Until then: please use max 99 points for modeling. You could limit them by choosing model with less stars, raising the horizon limit or remove them manually in the hemisphere window.

Sorry about that.

Michel:

PS: I added as many shortcuts as possible. The command protocol does right now not support more of them. I asked Filippo fro implementing more. We'll see what he could do.

**Comment by nickym998** [comment]
Many thanks Michel,

The software did report in the message window that only 100 points were going to be used. Reading the message window I also noticed some points had extreme errors (over 100,000) in dec and I think these are failed solves that are being included in the model somehow. After modelling I had over 300rms result so I quickly hit delete worse point twice and then gave me 8rms pointing.....

One further question. Should I use initial model tab for first 3points and then run full model? Or does the full model include the 3 base points?

Many thanks

Nick

**Comment by mworion** [comment]
Nick,
Basically the mount does not distinguish between the first three points an the rest. Have a look to
[
https://github.com/mworion/MountWizzard3-DIST/blob/master/docu/modelbuilding.md](url)
 As result full includes initial as well. Use initial, if the moutnneed basic alignment before doing much Points. If pointing is not much off, that just omit the initial points.

Michel

**Comment by nickym998** [comment]
Thanks Michel, 

What do you think about the bad model points? Should there be a sense check in software to stop erroneous model points?

Btw, That link above is broken:-
![8778a155-2736-4cb1-8ee0-44d39ad6a2d3](https://user-images.githubusercontent.com/42867242/46111874-7ab02780-c1e0-11e8-849b-0654ab9bb830.png)

**Comment by mworion** [comment]
Nick,

Next try for the link: 
https://github.com/mworion/MountWizzard3-DIST/blob/master/docu/modelbuilding.md
The mount computer accepts no model, which is to far off and rejects the points. I have seen that in some test, but I’m not sure, if that is enough. Checking that might be a good idea.

Michel

**Comment by mworion** [comment]
Hi Nick,

anything new about your observation with the remarks ?

Michel

**Comment by nickym998** [comment]
Hi Michel,

I managed to get a pretty good 64 point model after some deletions and since then have used this model each night for the recent spell of clear nights.  I haven’t built another model since but I am 100% confident that bad model points are somehow sent to the mount, resulting in huge RMS figures and the mount swings wildly about.  Only options when this happens are to quickly clear the whole model or keep pressing “delete worst model point” until I get a meaningful RMS figure.  Both of these actions stop the wild swinging of the mount.  I have used Per’s model Maker for the last few years without ever having this problem and have since switched back to this as the wild swinging of the mount worried me.

Please let me know if I can give you any further help,

Kind regards

Nick

**Comment by mworion** [comment]
Hi Nick,

finally manage to find the (a) bug. Out of your log file. In case of a certain solving error message I did not delete the result from plate solve, but included them still in model build. All other point went fine. This explains the whole behavior in your case. Will be solved in RC5. 

Michel

**Comment by nickym998** [comment]
Excellent Michel!

Really pleased you found it, I was pretty confident it was there!

Great work and greet piece of software,

Kind regards


Nick Morris

**Comment by mworion** [comment]
Close with RC5
