### ISSUE TITLE
Full model problem

### ISSUE THREAD

**Issue by gpassera** [mworion/MountWizzard3-DIST#17]
Hi.
I'm testing Mountwizzard3 after using version 2 with satisfaction.
I've a problem: I'm able to to the initial model (3 stars) without any problems but as soon as I run the full model (after placing a medium density pints ) nothing happen.
Mount won't run .
If I switch to version 2 with the same setup and same settings model will work and finish without any problem.
Any idea why the full model won't run?
Thank you.

I'm using SGP as imager, direct connection to my GM1000 hps (I can't find where to specify ascom driver to connect mount)

Giuseppe

**Comment by mworion** [comment]
Hi Giuseppe,

Sorry to hear that. Would you mind to post your logfile? 

Michel

**Comment by gpassera** [comment]
Hi Michel
Thank you for your answer. 
Attached  there is the log.

The problematic situation is the following:

[2019-01-01 21:01:05.534][   INFO][        model_build.py][   95][           doCommand][  Dummy-17] - Slewing to point  1  @ Az: 241° Alt: 25°
[2019-01-01 21:01:15.958][   INFO][      mountwizzard3.py][  982][     cancelFullModel][MainThread] - User canceled modeling

There is a slewing command but the mount won't move. After 10 secs I cancelled the operation.
The version that I'm using is the RC4 but the same is with RC5

Hope this help
Thank you and best regards
Giuseppe
[mount.2019-01-01.log](https://github.com/mworion/MountWizzard3-DIST/files/2720326/mount.2019-01-01.log)

**Comment by mworion** [comment]
Hi Giuseppe,

there was an issue in versions before RC5, which stopped modeling. This was fixed in RC5. Still I don't see an issue right there when using RC5. But anyway there is RC6 available these hours and the older should no be used anymore. Please give it a try with RC6

Michel
