### ISSUE TITLE
Full model problem (II)

### ISSUE THREAD

**Issue by gpassera** [mworion/MountWizzard3-DIST#18]
Hi Michel
I've installed RC6 but the problem persists.
Initial model works fine.
Full model works only if I choose the option to generatea grid of model points.
If I choose the option generate mode points based on greater circles the model won't start.
This is the log.
Any idea?
It's very frustrating...

Regards

Giuseppe

[mount.2019-01-07.log.zip](https://github.com/mworion/MountWizzard3-DIST/files/2734254/mount.2019-01-07.log.zip)

**Comment by mworion** [comment]
Giuseppe,

Sorry about it. Some question without seen the log (as I‘m currently on a business trip).
- do you have a horizon mask enabled ? If yes could you post a picture of the generated model points greater circle from hemisphere window ? 
Good hint that full model works with grid. So my guess with the known and solved issue ( which was in the modeling itself) was wrong, it seems to be a different one. 

Michel

**Comment by gpassera** [comment]
Michel 
this is my model.
I have only a limit  on 25 degree but not any particular mask.

<img width="1680" alt="screenshot 2019-01-07 at 21 03 45" src="https://user-images.githubusercontent.com/44640905/50835311-a9e54180-1356-11e9-9dc2-9de8520cfb62.png">

**Comment by gpassera** [comment]
Michael
I've done further tests and seems that the full model works only if I choose the "Generate a grid of model points"
If I choose  the model based on greater circles and also if I put the points by myself using the edit model point it doesn't work.
I tried also cancelling the 25degree limit but without any results.
Regards

Giuseppe

**Comment by mworion** [comment]
Hi Giuseppe,

unfortunately your zip file with the log is only 22Bytes, so something might happen. Could you post this again ?
Please have a look to the limits Horizon Lim (Low and High) on the Mount Data tab. The point have to be in these Limits. The difference I see so far, that the grid has minimum 40 degree altitude and the horizon you set is 25 degree. So we have to look on the limits itself.

Michel

**Comment by gpassera** [comment]
Michel
Problem solved.
The mount has an horizontal limit of 30degree and some points was below this limit, so the mount is not able to slew there.

I'm sorry but I forgot this.

Just a minor issue: in the mount data tab there is a HORION LIMIT that I think should be HORIZON LIMIT.
We can consider closed the issue.
Thank again and again many compliments for the program!!!
Ciao

Giuseppe


<img width="1680" alt="screenshot 2019-01-08 at 21 27 16" src="https://user-images.githubusercontent.com/44640905/50857039-aec4e800-138c-11e9-9f43-ff58a95e5455.png">

**Comment by gpassera** [comment]
Not an issue but my mistake.
