### ISSUE TITLE
smaller issues on Beta 5

### ISSUE THREAD

**Issue by fenriques** [mworion/MountWizzard3-DIST#2]
Hi Micheal,
Some minor issues, consider all these as low priority. 
I was testing without connecting the mount, so that could the cause of problems:
- in 'settings' 'enable remote access' flag and port number do not get saved when pressing 'save'.
- 'on' / 'off' buttons crash the app IF the mount is not connected.
- tooltips in 'position/relay' tab are not correct.
- 'site data' tab is not editable. Strange behaviour.
ferrante
PS: please stop me if reporting such issues is not useful.

**Comment by mworion** [comment]
Hi Ferrante,

thanks for the hint, I will fix theses bugs.

- Site data tab is intentionable not editable. So far MW takes the position the mount has. Reason for this is that many users have GPS connected and than we have more than on source.

Michel

**Comment by mworion** [comment]
HI,

beta 6 should address these issues.

**Comment by fenriques** [comment]
Good! I will test it tomorrow ( if the weather at my remote observatory in the alps is fine)
