### ISSUE TITLE
Plate Solving does not work in setup

### ISSUE THREAD

**Issue by mworion** [mworion/MountWizzard3-DIST#3]
Start of issue discussed with John

**Comment by jgusb** [comment]
Thanks Michel

I think these are the two you are looking for.

Gus

[Esprit_MW.zip](https://github.com/mworion/MountWizzard3-DIST/files/2108970/Esprit_MW.zip)
[mount.2018-06-12.zip](https://github.com/mworion/MountWizzard3-DIST/files/2108975/mount.2018-06-12.zip)

**Comment by mworion** [comment]
Hi Gus,

thanks for the log. Points directly to an issue which prevents solving. Will be corrected in beta 7.

Michel

**Comment by mworion** [comment]
…forgot: it’s online.
