### ISSUE TITLE
First Test of beta 6

### ISSUE THREAD

**Issue by fenriques** [mworion/MountWizzard3-DIST#4]
i had the chance to test mountwizzard 3 beta6 yesterday. I also updated the firmware to beta 14 in order to use WOL.
The main issues are:
- Whatever I tried I cannot solve any image. At first with 'initial model' it slewed to 3 stars (sometimes just 2) and capture, but it never solved 1 image (waited for 5 min).  The Astrometry log on my INDI client was not logging any activity like it didn't received any request. Connection setting tried were 127.0.0.1:7624, localhost:7624 and 192.168.3.48:7624 (my pc IP). No message in the message board (debug level).
Same was when I tried the 'image' section: camera was capturing images but when 'solve' was pushed it didn't start solving.
- the default for target RMS when optimizing a model is 0. First time it completely deleted my model! I suggest to set an higher default value.
- Whenever some action are performed e.g. change IP and save, turn off the mount etc the app freezes and it need to be force quit and restarted.

My setup is: Ubuntu Mate 16.04 and 10 Micron firmware beta 14.

**Comment by mworion** [comment]
1) there was a bug when accessing PIXSCALE in the fits header. This is addressed in beta 7. if I could check the log file, i could find out more.
2) default value: changed it to 99. makes sense to have a higher value. Will be in beta 8
3) should be addressed in already beta 7, changed reconnect and shutdown connection to mount

Try to check it on Ubuntu mate on raspi

If you don't mind, please attache the *.log file of your test

**Comment by mworion** [comment]
Hi thanks for the log.

as I could see, the problems seen in the log should be addressed in beta 7 as well (might not be all).  Some questions:
- do you see the camera / environment etc. status going to green for INDI settings ?
- if you go for settings - ip/INDI do you see the driver names of your chosen INDI server ?

What I learned, INDI itself work (taking images).
I see a problem seeting API key for astrometry. Did you set it right (if online), IP and PORT correct and Solver is green status ?

Michel

**Comment by fenriques** [comment]
attached a screenshot of my beta 7. i can see all green lights and drivers name.
About Astrometry, I'm using a local offline version. So i put 127.0.0.1 / localhost IP address and no API key. Am I using it right? 
![mwbeta7](https://user-images.githubusercontent.com/38842860/41564218-6d0539a4-7352-11e8-945f-0c39bf47bd3a.png)

**Comment by mworion** [comment]
No, there is the following situation:
- you used the INDI server as astrometry server. This does not work. INDI Server does not provide a astrometry.net web API. 
- I only could check if a server is running on a port, but checking does not distunguish between server types.
- I would recommend the astrometry-api-lite package from jussi (available on github) for local astrometry solution. This works very well and is tested from other linux users.

**Comment by fenriques** [comment]
ok, my bad, i didn't get it.
I just set up the astrometry-api-lite package and successfully test it with my last listen.fit that i found in my pc. 
I'm closing this thread as all the issues has been addressed.
Thanks.
