### ISSUE TITLE
Solver error on beta 7

### ISSUE THREAD

**Issue by fenriques** [mworion/MountWizzard3-DIST#5]
hi Michel,
I set up astrometry-api-light for solving. Still got an error on the fit file name or location,
It's in the log attached.
Thanks

[mount.2018-06-20.log](https://github.com/mworion/MountWizzard3-DIST/files/2117167/mount.2018-06-20.log)

**Comment by mworion** [comment]
hi ferrante,
could you describe, what you have done before ? Or do you have the image available what not could be loaded. The error I see is not related to solving, but loading a FIT's file

**Comment by fenriques** [comment]
hi Michel, 
it was an astropy version conflict within astrometry-api-lite. MountWizzard requires astropy 3.0.3 but astrometry-api-lite only works with 2.0.6 (it shows no error msg during installation but doesn't solve).
When you install astrometry-api-lite *after* mountwizard you'll have 3.0.3 already installed. Moreover astrometry-api-lite doesn't specify in the installation which pip version to use so you could find yourself using the wrong version. 
Jussi will  update the doc explicitly mentioning pip2.

Thanks and sorry for raising an issue that was not related to MountWizzard.
Ferrante
