### ISSUE TITLE
Further testing on beta 7

### ISSUE THREAD

**Issue by fenriques** [mworion/MountWizzard3-DIST#7]
Hi Michel,
- first of all, is there a forum where we can post questions without opening an issue (that probably are not even issues)?
- Using an horizon mask and then checking 'use minimum altitude' will alter the horizon mask file when you save the mask. I think that the minimum altitude should be used just like a dynamic overlay to the horizon mask not to effectively overwrite it.
- In the 'manage model' tab the points in the polar graph have colors ranging from green to red indicating the error. It could be useful to have a mousover effect with actual figures of RA / DEC errors.
- Solving online with astrometry.net works fine. Still I have issue with astrometry-api-lite. I will post logs later.

Ferrante

**Comment by mworion** [comment]
Ferrante,
you can keep going with the issues
No problem with it. Or you could use the 10micron forum.
Michel

**Comment by mworion** [comment]
Ferrante,

second point comment. saving follows the philisophy save what you see. If you would like to save without fixed mask, please switch it off. I would like to save a fully functional mask.

third point: agree, would be nice to have. I put it to the wishlist. A remark: the values of a single point is no that relevant for the model. There will be the anlalyses functions back, which are present in v2. If so, there will from my point no need to investigate a single point.

forth: please post the logs, I struggled a little bit, but got it to work.

Closing this issue now

Michel
